/*
 * generated by Xtext
 */
package ar.unq.edu.objetos3.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PdcUiModule extends ar.unq.edu.objetos3.ui.AbstractPdcUiModule {
	public PdcUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
