/**
 * generated by Xtext
 */
package ar.unq.edu.objetos3.ui.contentassist;

import ar.unq.edu.objetos3.ui.contentassist.AbstractPdcProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class PdcProposalProvider extends AbstractPdcProposalProvider {
}
