/*
 * generated by Xtext
 */
package ar.unq.edu.objetos3;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PdcRuntimeModule extends ar.unq.edu.objetos3.AbstractPdcRuntimeModule {

}
