/**
 * generated by Xtext
 */
package ar.unq.edu.objetos3.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#outline
 */
@SuppressWarnings("all")
public class PdcOutlineTreeProvider extends DefaultOutlineTreeProvider {
}
