/*
 * generated by Xtext
 */
package ar.unq.edu.objetos3.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractPdcValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(ar.unq.edu.objetos3.pdc.PdcPackage.eINSTANCE);
		return result;
	}
}
