/**
 * generated by Xtext
 */
package ar.unq.edu.objetos3.validation;

import ar.unq.edu.objetos3.validation.AbstractPdcValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class PdcValidator extends AbstractPdcValidator {
}
