/*
* generated by Xtext
*/
package ar.unq.edu.objetos3.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PdcAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("ar/unq/edu/objetos3/parser/antlr/internal/InternalPdc.tokens");
	}
}
