/*
* generated by Xtext
*/
package ar.unq.edu.objetos3.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import ar.unq.edu.objetos3.services.PdcGrammarAccess;

public class PdcParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private PdcGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected ar.unq.edu.objetos3.parser.antlr.internal.InternalPdcParser createParser(XtextTokenStream stream) {
		return new ar.unq.edu.objetos3.parser.antlr.internal.InternalPdcParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "PDC";
	}
	
	public PdcGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PdcGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
