/*
* generated by Xtext
*/
package ar.unq.edu.objetos3;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class PdcUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return ar.unq.edu.objetos3.ui.internal.PdcActivator.getInstance().getInjector("ar.unq.edu.objetos3.Pdc");
	}
	
}
