/*
 * generated by Xtext
 */
package ar.unq.edu.objetos3.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import ar.unq.edu.objetos3.ui.internal.PdcActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PdcExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return PdcActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return PdcActivator.getInstance().getInjector(PdcActivator.AR_UNQ_EDU_OBJETOS3_PDC);
	}
	
}
